use common::{Span, Spanned, VisibilityModifier, pool::DedupPoolId};
use smallvec::SmallVec;

use crate::{
    ASTExpression, ASTStatement, ComponentMember, ObjectField, StyleSheetStatement, SymbolPointer,
    Type, TypedName,
};

#[derive(Debug)]
///Represents a @name(...args). An Attribute is mainly used to define some metadata about the given declaration.
pub struct ASTAttribute {
    pub name: SymbolPointer,
    pub args: Vec<SymbolPointer>,
}

#[derive(Debug)]
pub struct GenericClause {
    //unimplemented at the moment. Represents a clause such as `where T: Thing`
    pub type_to_check: Spanned<DedupPoolId<Type>>,
    pub bounds: Vec<Spanned<DedupPoolId<Type>>>,
}

///Represents all the metadata about generics for a given declaration
#[derive(Debug)]
pub struct GenericsMetadata {
    ///The name of the generic parameter types. These can be generated by `func f<T,K>(){}`, which
    ///would have `type_params` of `["T", "K"]`.
    pub type_params: Vec<SymbolPointer>,
    ///The interfaces implemented by this generic declaration. These can be generated by `object MyObject: Interface1, Interface2 {}`
    ///where the types represent `Interface1` and `Interface2`.
    pub interface_implementations: Vec<Spanned<DedupPoolId<Type>>>,
    ///The clauses of this generic declaration, such as `where T: Thing`.
    pub clauses: Vec<Spanned<GenericClause>>,
}

impl GenericsMetadata {
    pub fn type_params(&self) -> &[SymbolPointer] {
        &self.type_params
    }
    pub fn interface_implementations(&self) -> &[Spanned<DedupPoolId<Type>>] {
        &self.interface_implementations
    }
    pub fn clauses(&self) -> &[Spanned<GenericClause>] {
        &self.clauses
    }
}

#[derive(Debug)]
pub struct ObjectMethod {
    pub visibility: VisibilityModifier,
    pub generics: GenericsMetadata,
    pub method_name: SymbolPointer,
    pub arguments: Vec<Spanned<TypedName>>,
    pub return_type: Spanned<DedupPoolId<Type>>,
    pub body: Vec<Spanned<DedupPoolId<ASTStatement>>>,
    pub span: Span,
}

#[derive(Debug)]
pub struct AliasDeclaration {
    ///The type parameters declared by this generic function. Each parameter is a
    ///`Type` (e.g. `Plain("T")`), so that use sites may later substitute any
    ///type, such as `[4]int`, for it.
    pub type_params: Vec<SymbolPointer>,
    pub name: SymbolPointer,
    pub target: Spanned<DedupPoolId<Type>>,
    pub span: Span,
    pub visibility: VisibilityModifier,
}
#[derive(Debug)]
pub struct ObjectDeclaration {
    pub generics: GenericsMetadata,
    pub name: SymbolPointer,
    pub fields: Vec<ObjectField>,
    pub methods: Vec<ObjectMethod>,
    pub attributes: Vec<Spanned<ASTAttribute>>,
    pub span: Span,
    pub visibility: VisibilityModifier,
    pub external: bool,
}
#[derive(Debug)]
pub struct ComponentDeclaration {
    pub generics: GenericsMetadata,
    pub name: SymbolPointer,
    pub members: Vec<ComponentMember>,
    pub attributes: Vec<Spanned<ASTAttribute>>,
    pub visibility: VisibilityModifier,
    pub span: Span,
    pub methods: Vec<ObjectMethod>,
}
#[derive(Debug)]
pub struct FuncDeclaration {
    pub generics: GenericsMetadata,
    pub name: SymbolPointer,
    pub args: Vec<Spanned<TypedName>>,
    pub return_type: Spanned<DedupPoolId<Type>>,
    pub body: Vec<Spanned<DedupPoolId<ASTStatement>>>,
    pub attributes: Vec<Spanned<ASTAttribute>>,
    pub visibility: VisibilityModifier,
    pub span: Span,
    pub external: bool,
}

///An interface declaration. This represents interfaces declarations such as the following:
///```text
///@myattribute
///pub interface Name<T,K>: SuperInterface, AnotherSuper where K: As<Bytes> {
/// func normalMethod(&self);
/// func normalMethod2(&mut self) -> int;
/// func owningMethod(self) {
///     //also containing default implementation
/// }
/// func staticMethod() -> int {
///     //static method with default implementation
/// }
/// func usingGenericMethod(&self, input: T) -> K;
///}
///```
#[derive(Debug)]
pub struct InterfaceDeclaration {
    pub generics: GenericsMetadata,
    pub name: SymbolPointer,
    pub methods: Vec<FuncDeclaration>,
    ///Always empty: the language has no syntax that names a super-interface of
    ///an interface. Kept so restoring that syntax only needs parser work.
    pub super_interfaces: Vec<Spanned<DedupPoolId<Type>>>,
    pub attributes: Vec<Spanned<ASTAttribute>>,
    pub visibility: VisibilityModifier,
    pub span: Span,
}
#[derive(Debug)]
pub struct ExtendDeclaration {
    pub generics: GenericsMetadata,
    pub target: Spanned<DedupPoolId<Type>>,
    pub methods: Vec<FuncDeclaration>,
    pub attributes: Vec<Spanned<ASTAttribute>>,
    pub span: Span,
}

#[derive(Debug)]
pub struct StyleSheet {
    pub name: SymbolPointer,
    pub generics: GenericsMetadata,
    pub args: Vec<Spanned<TypedName>>,
    pub usages: Vec<Spanned<DedupPoolId<ASTExpression>>>,
    pub body: Vec<Spanned<StyleSheetStatement>>,
    pub attributes: Vec<Spanned<ASTAttribute>>,
    pub visibility: VisibilityModifier,
    pub span: Span,
}
#[derive(Debug)]
pub struct StaticDeclaration {
    pub name: SymbolPointer,
    pub ty: Spanned<DedupPoolId<Type>>,
    pub value: Option<Spanned<DedupPoolId<ASTExpression>>>, //option because, if not provided, it yet can be used, even though might lead to runtime bugs. Should be None only on externs
    pub attributes: Vec<Spanned<ASTAttribute>>,
    pub visibility: VisibilityModifier,
    pub span: Span,
    pub external: bool,
}

#[derive(Debug)]
pub enum EnumVariantKind {
    ///represents a raw variant, such as 'Name' in `enum N {Name}`
    Raw,
    ///represents a raw valued variant, such as 'Name' in `enum N {Name = 5}`
    RawValued(Spanned<DedupPoolId<ASTExpression>>),
    ///represents an associated variant, such as 'Name' in `enum N {Name(int)}`
    Associated(SmallVec<[Spanned<DedupPoolId<Type>>; 2]>),
    ///represents a struct variant, such as 'Name' in `enum N {Name { <fields> }}`
    Struct(SmallVec<[Spanned<TypedName>; 2]>),
}

#[derive(Debug)]
pub struct EnumVariant {
    ///Name of the variant
    pub name: Spanned<SymbolPointer>,
    ///The kind of the variant
    pub kind: EnumVariantKind,
    ///The attributes of the variant
    pub attributes: Vec<Spanned<ASTAttribute>>,
    pub span: Span,
}

#[derive(Debug)]
pub struct EnumDeclaration {
    ///The name of the enum
    pub name: SymbolPointer,
    pub generics: GenericsMetadata,
    ///What representation to use for this enum. Only valid with all variants being Raw or RawValued
    pub representation: Option<Spanned<DedupPoolId<Type>>>,
    pub variants: Vec<EnumVariant>,
    pub attributes: Vec<Spanned<ASTAttribute>>,
    pub visibility: VisibilityModifier,
    pub span: Span,
    pub methods: Vec<ObjectMethod>,
}

#[derive(Debug)]
pub struct StyleState {
    pub states: Vec<SymbolPointer>,
    pub duration: Option<Spanned<DedupPoolId<ASTExpression>>>,
    pub transition_curve: Option<SymbolPointer>,
}

impl Default for StyleState {
    fn default() -> Self {
        Self::new()
    }
}

impl StyleState {
    pub fn new() -> Self {
        Self {
            states: Vec::new(),
            duration: None,
            transition_curve: None,
        }
    }
}

///A trait that represents a type that can be used as a function. This can use used to represent function them selves, object methods, closures, etc.
pub trait ASTFunction {
    fn method_name(&self) -> SymbolPointer;
    fn arguments(&self) -> &[Spanned<TypedName>];
    fn return_type(&self) -> Spanned<DedupPoolId<Type>>;
    fn body(&self) -> &[Spanned<DedupPoolId<ASTStatement>>];
    fn generics(&self) -> &GenericsMetadata;
    fn span(&self) -> Span;
}

impl ASTFunction for ObjectMethod {
    fn generics(&self) -> &GenericsMetadata {
        &self.generics
    }
    fn method_name(&self) -> SymbolPointer {
        self.method_name
    }

    fn arguments(&self) -> &[Spanned<TypedName>] {
        &self.arguments
    }

    fn return_type(&self) -> Spanned<DedupPoolId<Type>> {
        self.return_type
    }

    fn body(&self) -> &[Spanned<DedupPoolId<ASTStatement>>] {
        &self.body
    }

    fn span(&self) -> Span {
        self.span
    }
}
impl ASTFunction for FuncDeclaration {
    fn generics(&self) -> &GenericsMetadata {
        &self.generics
    }
    fn arguments(&self) -> &[Spanned<TypedName>] {
        &self.args
    }
    fn body(&self) -> &[Spanned<DedupPoolId<ASTStatement>>] {
        &self.body
    }
    fn method_name(&self) -> SymbolPointer {
        self.name
    }
    fn return_type(&self) -> Spanned<DedupPoolId<Type>> {
        self.return_type
    }

    fn span(&self) -> Span {
        self.span
    }
}
